import '@/styles/reset.css'
import '@/styles/globals.css'
import Nav from '@/components/Nav'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
          <div className="w-full flex-none md:w-64">
            <Nav />
          </div>
          <div className="flex-grow flex overflow-y-auto mx-8">{children}</div>
        </div>
      </body>
    </html>
  )
}
